### ISSUE TITLE
Broken README rendering on pypi.python.org

### ISSUE THREAD

**Issue by invisiblefunnel** [remix/partridge#12]
Any ideas?

<img width="570" alt="screenshot 2017-12-10 11 41 54" src="https://user-images.githubusercontent.com/331023/33808669-4bedc914-dd9f-11e7-8a55-632272f08b4d.png">

**Comment by kuanb** [comment]
Late to the party but I noticed the same issue on Peartree. I used https://pypi.python.org/pypi/restructuredtext_lint and was able to identify issues that were passing locally but preventing content from rendering correctly on pypi. Still haven't updated the package there, so who knows if I was actually successful!
