### ISSUE TITLE
Parent stations missing from feed

### ISSUE THREAD

**Issue by cjer** [remix/partridge#20]
* partridge version: 0.3.0
* Python version: 3.6

### Description

The filtering that takes place right now omits `parent_station`s from `stops` since they don't have any actual stops. 

I think these shouldn't be filtered out. 

### What I Did

```
import partridge as ptg

service_ids_by_date = ptg.read_service_ids_by_date(LOCAL_ZIP_PATH)
service_ids = service_ids_by_date[datetime.date(2017, 12, 21)]

feed = ptg.feed(LOCAL_ZIP_PATH, view={
    'trips.txt': {
        'service_id': service_ids,
    },
})

s = feed.stops
s[s.stop_id.isin(s.parent_station.value_counts().head(10).index)]
```
This gave back an empty DataFrame, but once I took `s.parent_station.value_counts().head(10).index)` and used it to slice a DataFrame built by reading the `stops.txt` csv, I got them all back.

**Comment by invisiblefunnel** [comment]
Thanks, @cjer. I'll take a look this weekend. Is the GTFS file you're working with available at a URL? Would like to debug with the same data.

**Comment by cjer** [comment]
Sure @invisiblefunnel, you can find it [here](https://transitfeeds.com/p/ministry-of-transport-and-road-safety/820).

Tell me if there's anything else you need to know, or want help with it.

**Comment by invisiblefunnel** [comment]
My understanding is that `parent_station`s which aren't referenced from `stop_times.txt` are pruned from the stops dataframe. Partridge isn't accounting for the self-loop from `stops.parent_station` to `stops.stop_id`.

**Comment by cjer** [comment]
That's also how I understood it. Do you think that could be fixed just by playing with the conf?

Oh and if you go on working with the feed I linked to, stop names are in Hebrew so I guess it would make less sense to you if you don't speak. The top parent stations are valid central stations and big terminals.

**Comment by invisiblefunnel** [comment]
> Do you think that could be fixed just by playing with the conf?

Not as it exists now because the config graph can't have cycles. I'll think more about it. The ultimate solution if you need parent stations might be not to prune stops.

**Comment by invisiblefunnel** [comment]
Example workaround:

```python
config = ptg.config.default_config()
config.remove_edges_from(list(config.out_edges('stops.txt')))
feed = ptg.feed('path/to/gtfs.zip', config)
```

**Comment by invisiblefunnel** [comment]
I'm going to mark this as `wontfix` for now. Please use the workaround above if `parent_station`s are important to your work.
