### ISSUE TITLE
Read the Docs

### ISSUE THREAD

**Issue by tilgovi** [remix/partridge#34]
Let's get Read the Docs building the documentation and then we can link to an online version.

**Comment by tilgovi** [comment]
I've set up the project, but it's failing to build. It's been a while since I've done this so I forget how :).

**Comment by invisiblefunnel** [comment]
I approved third-party access for Read the Docs.

**Comment by tilgovi** [comment]
http://partridge.readthedocs.io/en/latest/

**Comment by OrBin** [comment]
This is broken again.
I'm getting a **401 Permission Denied** response with the message:
`
You don't have the proper permissions to view this page. Please contact the owner of this project to request permission.
`

What's going on with this?

**Comment by invisiblefunnel** [comment]
I turned off the readthedocs page because the last working build of the page was way outdated and misleading. Seemed better to take the page offline until the build is fixed.

FWIW I'd love help from the community to get the latest docs online. I don't have the time now, unfortunately. Thanks for understanding.

**Comment by OrBin** [comment]
I can try and help, I've already configured RTD for another project before. I'll just need permissions for the RTD project to do so.

**Comment by invisiblefunnel** [comment]
Thank you! I've added you as a maintainer on RTD.

**Comment by OrBin** [comment]
Fixed! You just had to go to `Admin > Advanced Settings` > Requirements file` and set `requirements_dev.txt` as the requirements file. Then the build passed :)

**Comment by tilgovi** [comment]
Thanks, @OrBin!

**Comment by invisiblefunnel** [comment]
Thank you!
