### ISSUE TITLE
detect_encoding very time consuming

### ISSUE THREAD

**Issue by cjer** [remix/partridge#39]
* partridge version: 0.10.0
* Python version: 3.6
* Operating System: Win10

I'm working on using partridge to speed up statistical summarization of a historical archive of feeds, so I made some kind of a mashup between partridge and GTFSTK, you can see an initial version [here](https://github.com/cjer/open-bus-explore/blob/master/gtfs_stats.py).

I profiled the run and noticed that `detect_encoding` is responsible for about half of partridge's run time. I am sure this could be alleviated somehow by specifying the encoding if it is known upfront. 

![image](https://user-images.githubusercontent.com/9987721/42723474-10409550-8767-11e8-86f2-8ae1f7e40e53.png)

**Comment by invisiblefunnel** [comment]
Looks like something we need to fix! Can you post a GTFS zip that exhibits this behavior?

**Comment by cjer** [comment]
chardet is probably indecisive for some reason.
this one should do - ftp://gtfs.mot.gov.il/israel-public-transportation.zip

I added a quick local fix by just adding an encoding attribute to the feed class, which defaults to None. When set to anything else, it bypasses detect_encoding. It cut run time by more than half.

**Comment by cjer** [comment]
(that of course also meant adding it as a parameter to the relevant reader I was using `read_service_ids_by_date`, and to `raw_feed`)

**Comment by invisiblefunnel** [comment]
Merged #40. Released as v0.11.0.

https://pypi.org/project/partridge/#history
