### ISSUE TITLE
write_feed_dangerously usage

### ISSUE THREAD

**Issue by cjer** [remix/partridge#41]
* partridge version: 0.10.0

I would like to have the option for creating a valid pruned GTFS feed based on a partridge feed. 
I tried to use `write_feed_dangerously`, but:

1. I can't seem to figure out how to get back to a partridge feed from this.  Can this be easily done somehow?
1. I have noticed it really isn't a valid GTFS feed. Is there any plan or work in progress for doing so?

Thanks

**Comment by invisiblefunnel** [comment]
Hi @cjer. I recommend using `ptg.writers.extract_feed`, instead of using `write_feed_dangerously`.

```python
inpath = 'mygtfs.zip'
outpath = 'mygtfs-pruned.zip'
agency_ids = ['2', '4']

ptg.writers.extract_feed(inpath, outpath, {
    {'routes.txt': {'agency_id': agency_ids}}
})

feed = ptg.feed(outpath)
```

Does that work for your use case?

**Comment by cjer** [comment]
Hey! that seems to work great! 

docs anyone? :)

**Comment by invisiblefunnel** [comment]
I recently added `extract_feed` to the docs under "Extracting a new feed" in the Usage section: https://github.com/remix/partridge#usage.
