### ISSUE TITLE
Output date format is incorrect

### ISSUE THREAD

**Issue by tilgovi** [remix/partridge#53]
* partridge version: v1.0.0
* Python version: v3.7.1
* Operating System: macOS

### Description

Writing a feed results in date columns represented as '%Y-%m-%d' where they should be '%Y%m%d'. The reader code correctly parses dates in the feeds, but the writer does not write them in the same format.

**Comment by invisiblefunnel** [comment]
This is related to the usage of a semi-private function. See #52 for more context.
