### ISSUE TITLE
Frequencies by route for a given time period

### ISSUE THREAD

**Issue by bhargavasana** [remix/partridge#65]
* partridge version: 1.1.1
* Python version: 3.8
* Operating System: Windows 10

### Description

Is there a recipe or notebook for obtaining service frequencies or average headways by route for a give time period (say 6am-9am)?

### What I Did

I looked at the notebooks in the wiki and could not find what I was looking for.

Thank you!

**Comment by invisiblefunnel** [comment]
This is a tricky problem to solve in the general case. I added an example to the wiki that [approximates headway for a particular stop](https://gist.github.com/invisiblefunnel/6015e65684325281e65fa9339a78229b).
