### ISSUE TITLE
numpy attribute issue in gtfs.py

### ISSUE THREAD

**Issue by mluc08** [remix/partridge#77]
* partridge version:
* Python version:
* Operating System:

### Description

Code stoppe running properly due to package error

### What I Did

line 102, in _read_csv df = pd.read_csv(path, dtype=np.unicode, encoding=encoding, index_col=False) File "/home/site/wwwroot/.python_packages/lib/site-packages/numpy/__init__.py", 
line 284, in __getattr__ raise AttributeError("module {!r} has no attribute "

**Comment by amillb** [comment]
I think this is a simple fix to line 92 of `gtfs.py`.

Per the `numpy` docs ([see the Deprecations section](https://github.com/numpy/numpy/releases/tag/v1.20.0), line 92 just needs `np.unicode` to be replaced by `str`.

I would make a pull request but I'm not familiar with this process.
